spring.application.name=banking

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:hdfcdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (browser access)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true




jwt.secret=hdfc-banking-super-secret-key-must-be-at-least-32-chars!!
jwt.expiration=86400000
